# Generated by Django 5.0.4 on 2024-04-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes')),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
